# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - .env
    
    depends_on:
      db:
        condition: service_started

volumes:
  postgres_volume: